# This is the configuration for the home cluster
# for the Pi-hole application.
# It includes a custom list for DNS resolution.
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-dnsmasq-config
  namespace: pihole
  labels:
    app: pihole
data:
  99-wildcard.conf: |
    address=/.kintbury/10.0.0.120
