# This is the configuration for the home cluster
# for the Pi-hole application.
# It includes a custom list for DNS resolution.
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-custom-list
  namespace: pihole
data:
  custom.list: |
    10.0.0.103 grafana.local
    10.0.0.100 pihole.local
