# DNS Service for Primary Deployment
kind: Service
apiVersion: v1
metadata:
  name: pihole-dns-primary
  namespace: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  selector:
    app: pihole
    role: primary
  ports:
    - port: 53
      targetPort: 53
      name: pihole-dns-udp
      protocol: UDP
    - port: 53
      targetPort: 53
      name: pihole-dns-tcp
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 10.0.0.100
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local
---

# DNS Service for Secondary Deployment
kind: Service
apiVersion: v1
metadata:
  name: pihole-dns-secondary
  namespace: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  selector:
    app: pihole
    role: secondary
  ports:
    - port: 53
      targetPort: 53
      name: pihole-dns-udp
      protocol: UDP
    - port: 53
      targetPort: 53
      name: pihole-dns-tcp
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 10.0.0.101 # Use a separate IP for the secondary DNS service
  sessionAffinity: ClientIP
---

# Web Interface for Primary Deployment
kind: Service
apiVersion: v1
metadata:
  name: pihole-lb
  namespace: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  selector:
    app: pihole
    role: primary
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
    - port: 443
      targetPort: 443
      name: https
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 10.0.0.100 # Same IP as the primary DNS service
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local

---

kind: Service
apiVersion: v1
metadata:
  name: pihole-svc
  namespace: pihole
spec:
  selector:
    app: pihole
    role: primary
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
    - port: 443
      targetPort: 443
      name: https
      protocol: TCP