apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc-pihole
  namespace: pihole
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
