apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-selfsigned-cert
  namespace: pihole
spec:
  secretName: pihole-tls-secret     # cert-manager will create/manage this Secret
  duration: 2160h                   # 90 days (optional)
  renewBefore: 360h                 # 15 days (optional)
  dnsNames:
    - pihole.kintbury
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer