apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc-pihole
  namespace: pihole
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
