apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
    role: secondary
  name: pihole-ro
  namespace: pihole
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
        role: secondary
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: pihole-config
          persistentVolumeClaim:
            claimName: pihole-pvc-pihole
        - name: pihole-dnsmasq
          persistentVolumeClaim:
            claimName: pihole-pvc-dnsmasq
        - name: pihole-custom-list
          configMap:
            name: pihole-custom-list
        - name: pihole-adlists-list
          configMap:
            name: pihole-adlists-list
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pihole
                - key: role
                  operator: In
                  values:
                  - secondary
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: pihole
          image: pihole/pihole:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "50Mi"
              cpu: "250m"
            limits:
              memory: "100Mi"
              cpu: "500m"
          env:
            - name: TZ
              value: Europe/London
            - name: DNS1
              value: 1.1.1.1
            - name: DNSMASQ_LISTENING
              value: all
            - name: FTLCONF_CHECK_DISK
              value: "0"
          ports:
            - containerPort: 53
              name: pihole-dns-tcp
              protocol: TCP
            - containerPort: 53
              name: pihole-dns-udp
              protocol: UDP
          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole-config
            - mountPath: /etc/pihole/custom.list
              name: pihole-custom-list
              readOnly: true
              subPath: custom.list
            - mountPath: /etc/pihole/adlists.list
              name: pihole-adlists-list
              subPath: adlists.list
              readOnly: true
            - mountPath: /etc/dnsmasq.d
              name: pihole-dnsmasq
          livenessProbe:
            exec:
              command:
              - dig
              - "@127.0.0.1"
              - google.com
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
              - dig
              - "@127.0.0.1"
              - google.com
            initialDelaySeconds: 30
            periodSeconds: 10

