apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-ingress
  namespace: pihole
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/proxy-buffering: 'off'
    nginx.ingress.kubernetes.io/proxy-cookie-path: / /
    nginx.ingress.kubernetes.io/proxy-pass-headers: Set-Cookie
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: PIHOLE_SESSION
spec:
  rules:
  - host: pihole.kintbury
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: pihole-svc
            port:
              number: 80